
import java.util.Scanner;

class Student {
    Scanner sc = new Scanner(System.in);
    double[] marks_array;
    String s_name;
    double avg;
    double total;
    int n;

    Student() {
        System.out.println("Enter the Number of Subjects: ");
        n = sc.nextInt();
        sc.nextLine(); // consume the newline character(\n) generated by .nextInt()
        marks_array = new double[n];
    }

    void assign() {
        System.out.print("What is the Name: ");
        s_name = sc.nextLine();
        System.out.println("\nEnter marks of subject: ");
        for (int i = 0; i < marks_array.length; i++) {
            System.out.print("suject " + (i + 1) + " ");
            marks_array[i] = sc.nextDouble();
        }
    }

    void compute() {
        for (int i = 0; i < marks_array.length; i++) {
            total += marks_array[i];
        }
        avg = total / marks_array.length;
    }
}

public class Ex1 {
    public static void main(String[] args) {

        Student Aman = new Student();

        Aman.assign();
        Aman.compute();
        System.out.println("Average marks: " + Aman.avg);
        System.out.println("Total marks: " + Aman.total);
    }
}